-- MySQL Script generated by MySQL Workbench
-- Wed Jan 19 12:54:22 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema res_httr
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema res_httr
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `res_httr` DEFAULT CHARACTER SET utf8 ;
USE `res_httr` ;

-- -----------------------------------------------------
-- Table `res_httr`.`study`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `res_httr`.`study` (
  `study_id` INT NOT NULL AUTO_INCREMENT,
  `celltype` VARCHAR(45) NULL,
  `dataset` VARCHAR(255) NULL,
  `time` INT NULL,
  `media` VARCHAR(45) NULL,
  `shrinkage` VARCHAR(45) NULL,
  `plate_effect` VARCHAR(45) NULL,
  `species` VARCHAR(45) NULL,
  `hashkey` TEXT NULL,
  `datestamp` DATETIME NULL,
  PRIMARY KEY (`study_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `res_httr`.`chemical`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `res_httr`.`chemical` (
  `dtxsid` VARCHAR(45) NOT NULL,
  `casrn` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `hashkey` TEXT NULL,
  `datestamp` DATETIME NULL,
  PRIMARY KEY (`dtxsid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `res_httr`.`sample`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `res_httr`.`sample` (
  `sample_id` VARCHAR(45) NOT NULL,
  `dtxsid` VARCHAR(45) NOT NULL,
  `hashkey` TEXT NULL,
  `datestamp` DATETIME NULL,
  PRIMARY KEY (`sample_id`),
  INDEX `fk_sample_chemical1_idx` (`dtxsid` ASC),
  CONSTRAINT `fk_sample_chemical1`
    FOREIGN KEY (`dtxsid`)
    REFERENCES `res_httr`.`chemical` (`dtxsid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `res_httr`.`signature`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `res_httr`.`signature` (
  `signature_id` INT NOT NULL AUTO_INCREMENT,
  `signature` VARCHAR(255) NOT NULL,
  `parent` VARCHAR(255) NULL,
  `source` VARCHAR(45) NULL,
  `subsource` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `direction` VARCHAR(45) NULL,
  `ngene` VARCHAR(45) NULL,
  `description` TEXT NULL,
  `super_target` VARCHAR(45) NULL,
  `effect_direction` VARCHAR(45) NULL,
  `target_class` VARCHAR(45) NULL,
  `super_target_level` VARCHAR(45) NULL,
  `genelist` TEXT NULL,
  `hashkey` TEXT NULL,
  `datestamp` DATETIME NULL,
  PRIMARY KEY (`signature_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `res_httr`.`signature_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `res_httr`.`signature_list` (
  `signature_list_id` INT NOT NULL,
  `sigset` VARCHAR(45) NOT NULL,
  `signature` VARCHAR(255) NULL,
  `hashkey` TEXT NULL,
  `datestamp` DATETIME NULL,
  PRIMARY KEY (`signature_list_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `res_httr`.`concresp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `res_httr`.`concresp` (
  `concresp_id` INT NOT NULL AUTO_INCREMENT,
  `sample_id` VARCHAR(45) NOT NULL,
  `dtxsid` VARCHAR(45) NOT NULL,
  `dataset` VARCHAR(255) NULL,
  `method` VARCHAR(45) NULL,
  `sigset` VARCHAR(45) NULL,
  `signature` VARCHAR(255) NULL,
  `n_gt_cutoff` INT NULL,
  `cutoff` DOUBLE NULL,
  `fit_method` VARCHAR(45) NULL,
  `top_over_cutoff` DOUBLE NULL,
  `rmse` DOUBLE NULL,
  `a` DOUBLE NULL,
  `b` DOUBLE NULL,
  `tp` DOUBLE NULL,
  `p` DOUBLE NULL,
  `q` DOUBLE NULL,
  `ga` DOUBLE NULL,
  `la` DOUBLE NULL,
  `er` DOUBLE NULL,
  `bmr` DOUBLE NULL,
  `bmdl` DOUBLE NULL,
  `bmdu` DOUBLE NULL,
  `caikwt` DOUBLE NULL,
  `mll` DOUBLE NULL,
  `hitcall` DOUBLE NULL,
  `ac50` DOUBLE NULL,
  `ac50_loss` DOUBLE NULL,
  `top` DOUBLE NULL,
  `ac5` DOUBLE NULL,
  `ac10` DOUBLE NULL,
  `ac20` DOUBLE NULL,
  `acc` DOUBLE NULL,
  `ac1sd` DOUBLE NULL,
  `bmd` DOUBLE NULL,
  `conc` VARCHAR(255) NULL,
  `resp` VARCHAR(255) NULL,
  `bmr_scale` DOUBLE NULL,
  `hashkey` TEXT NULL,
  `datestamp` DATETIME NULL,
  PRIMARY KEY (`concresp_id`),
  INDEX `fk_concresp_sample1_idx` (`sample_id` ASC, `dtxsid` ASC),
  CONSTRAINT `fk_concresp_sample1`
    FOREIGN KEY (`sample_id`)
    REFERENCES `res_httr`.`sample` (`sample_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `res_httr`.`pod`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `res_httr`.`pod` (
  `pod_id` INT NOT NULL AUTO_INCREMENT,
  `sample_id` VARCHAR(45) NOT NULL,
  `dtxsid` VARCHAR(45) NOT NULL,
  `dataset` VARCHAR(255) NULL,
  `method` VARCHAR(45) NULL,
  `pod_method` VARCHAR(45) NULL,
  `pod` DOUBLE NULL,
  `pod_uci` DOUBLE NULL,
  `pod_lci` DOUBLE NULL,
  `hashkey` TEXT NULL,
  `datestamp` DATETIME NULL,
  PRIMARY KEY (`pod_id`),
  INDEX `fk_pod_sample1_idx` (`sample_id` ASC, `dtxsid` ASC),
  CONSTRAINT `fk_pod_sample1`
    FOREIGN KEY (`sample_id`)
    REFERENCES `res_httr`.`sample` (`sample_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
